name: Integration Benchmark

on:
  workflow_dispatch:
    inputs:
      REPOSITORY_URL:
        description: "REPOSITORY_URL"
        required: true
      BRANCH_NAME:
        description: 'BRANCH_NAME'
        required: true
#      CIRCUIT:
#        description: 'CIRCUIT_NAME'
#        required: true
      PROVER:
        description: 'Select Prover'
        required: true
        type: choice
        options: ["Mock", "Real"]
env:
  BENCH_RESULTS_PASS: ${{ secrets.BENCH_RESULTS_PASS }}

jobs:
  integration_benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup
        run: |
          cd .github/weeklyBenchScripts
          ./github-action-setup.sh
        env:
          GITHUB_RUN_ID: ${{ vars.GITHUB_RUN_ID }}

      - name: Trigger
        run: |
          cd .github/integrationBenchScripts
          ./github-action-trigger.sh
        env:
          GITHUB_RUN_ID: ${{ vars.GITHUB_RUN_ID }}
          REPOSITORY_URL: ${{ inputs.REPOSITORY_URL || github.event.client_payload.REPOSITORY_URL }}
          BRANCH_NAME: ${{ inputs.BRANCH_NAME || github.event.client_payload.BRANCH_NAME }}
#          CIRCUIT: ${{ inputs.CIRCUIT || github.event.client_payload.CIRCUIT }}
          PROVER: ${{ github.event.inputs.PROVER }}

      - name: Cleanup
        run: |
          cd .github/weeklyBenchScripts
          ./github-action-cleanup.sh
        if: always()
        env:
          GITHUB_RUN_ID: ${{ vars.GITHUB_RUN_ID }}
